default:
  image: python:3.8

variables:
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip
  POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pypoetry
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  POSTGRES_DB: tests
  POSTGRES_USER: meshmap
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - prep
  - test

build:
  # Confirm Poetry can build - and warm up the cache
  stage: prep
  script:
    - apt-get update
    - apt-get install -y librrd-dev
    - pip install poetry
    - poetry install
  cache:
    paths:
      - .cache/pip
      - .cache/pypoetry

pre-commit:
  stage: test
  script:
    - pip install pre-commit poetry
    - pre-commit run --all-files
  cache:
    key: pre-commit
    paths:
      - .cache/pip
      - .cache/pre-commit
    policy: pull

# Template to prepare Poetry (for use with `extends`)
.poetry:
  before_script:
    - apt-get update
    - apt-get install -y librrd-dev
    - pip install poetry
    - poetry install

flake8:
  stage: test
  extends: .poetry
  script:
    - poetry run flake8 pymeshmap tests --format=junit-xml --output=flake8-report.xml
  artifacts:
    reports:
      junit: flake8-report.xml
  cache:
    paths:
      - .cache/pip
      - .cache/pypoetry
    policy: pull

mypy:
  stage: test
  extends: .poetry
  script:
    - poetry run mypy pymeshmap --junit-xml=mypy-report.xml
  artifacts:
    reports:
      junit: mypy-report.xml
  cache:
    paths:
      - .cache/pip
      - .cache/pypoetry
    policy: pull

# Template for pytest to simplify testing different versions of Python
.pytest:
  stage: test
  extends: .poetry
  services:
    - postgres:12
  script:
    - poetry run pytest --cov=pymeshmap --junit-xml=pytest-report.xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      junit: pytest-report.xml

pytest 3.7:
  extends: .pytest
  image: python:3.7
  cache:
    key: poetry37
    paths:
      - .cache/pip
      - .cache/pypoetry

pytest 3.8:
  extends: .pytest
  image: python:3.8
  cache:
    paths:
      - .cache/pip
      - .cache/pypoetry
    policy: pull

pytest 3.9:
  extends: .pytest
  image: python:3.9
  cache:
    key: poetry39
    paths:
      - .cache/pip
      - .cache/pypoetry

pytest 3.10:
  extends: .pytest
  image: python:3.10
  cache:
    key: poetry310
    paths:
      - .cache/pip
      - .cache/pypoetry
