[tool.poetry]
name = "pymeshmap"
version = "0.1.0"
description = "Application for crawling and mapping an AREDN network."
authors = ["Scott Searcy <ki7onk@outlook.com>"]
readme = "README.md"
repository = "https://gitlab.com/smsearcy/pymeshmap"

[tool.isort]
profile = "black"
multi_line_output = 3
known_third_party = "alembic"

[tool.poetry.scripts]
pymeshmap = "pymeshmap.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4"
loguru = "^0.5.0"
attrs = "^21.2.0"
psycopg2 = "^2.8.5"
sqlalchemy = "^1.4.17"
python-dotenv = "^0"
alembic = "^1.4.3"
environ-config = "^21.2.0"
pyramid = "^2.0"
waitress = "^2.0.0"
pyramid-retry = "^2.1.1"
pyramid-tm = "^2.4"
transaction = "^3.0.1"
"zope.sqlalchemy" = "^1.3"
pyramid-services = "^2.2"
pyramid-jinja2 = "^2.8"
pendulum = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.0"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
flake8-bugbear = "^21.3.1"
flake8_formatter_junit_xml = "^0.0.6"
mypy = "^0"
Faker = "^8.0.0"
pytest-asyncio = "^0.15.1"
pytest-mock = "^3.3.1"
pyramid-debugtoolbar = "^4.9"
WebTest = "^2.0.35"
pytest-postgresql = "^3.0.0"
types-waitress = "^0.1.4"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
