[tool.poetry]
name = "pymeshmap"
version = "0.1.0"
description = "Application for crawling and mapping an AREDN network."
authors = ["Scott Searcy <ki7onk@outlook.com>"]
readme = "README.md"
repository = "https://gitlab.com/smsearcy/pymeshmap"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.poetry.scripts]
pymeshmap = "pymeshmap.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = {extras = ["speedups"], version = "^3.6.2"}
loguru = "^0.5.0"
attrs = "^20.3.0"
psycopg2 = "^2.8.5"
sqlalchemy = "^1.3.18"
python-dotenv = "^0.14.0"
alembic = "^1.4.3"
environ-config = "^20.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
flake8_formatter_junit_xml = "^0.0.6"
mypy = "^0.780"
Faker = "^4.1.0"
pytest-asyncio = "^0.14.0"
pytest-mock = "^3.3.1"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
