[tool.poetry]
name = "pymeshmap"
version = "0.1.0"
description = "Application for crawling and mapping AREDwork."
authors = ["Scott Searcy <smsearcy14@outlook.com>"]
readme = "README.md"
repository = "https://gitlab.com/smsearcy/pymeshmap"


[tool.poetry.scripts]
# Uncomment for CLI entrypoint
# pymeshmap = "pymeshmap.pymeshmap:main"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
flake8_formatter_junit_xml = "^0.0.6"
mypy = "^0.780"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
