[tool.poetry]
name = "pymeshmap"
version = "0.1.0"
description = "Application for crawling and mapping an AREDN network."
authors = ["Scott Searcy <smsearcy14@outlook.com>"]
readme = "README.md"
repository = "https://gitlab.com/smsearcy/pymeshmap"

[tool.poetry.scripts]
pymeshmap = "pymeshmap.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = {extras = ["speedups"], version = "^3.6.2"}
loguru = "^0.5.0"
click = "^7.1.2"
attrs = "^19.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
flake8_formatter_junit_xml = "^0.0.6"
mypy = "^0.780"
Faker = "^4.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
